name: tests

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install pipenv
            pipenv install --dev
            python -m pip install -e .
            python -m pip install cmudict nltk pyphen pytest unidecode stanza --quiet
      - name: Run tests
        env:
          NLTK_DATA: ${{ github.workspace }}/smoothtext/data/nltk_data
        run: |
            pipenv run pytest
